import { AttendanceStatus } from '@prisma/client';

export type AttendanceSeverity = 'POSITIVE' | 'LOW' | 'MEDIUM' | 'HIGH' | 'NEUTRAL';

export type AttendancePolicyItem = {
  countsAsPresence: boolean;
  countsAsAbsence: boolean;
  isJustifiedAbsence: boolean;
  reliabilityImpact: number;
  engagementImpact: number;
  eligibilityImpact: number;
  pastoralAlert: boolean;
  triggersJourneyEvent: boolean;
  includedInAnalytics: boolean;
  includedInReports: boolean;
  includedInDashboard: boolean;
  generatesTimeline: boolean;
  triggersAutomation: boolean;
  severity: AttendanceSeverity;
};

export const ATTENDANCE_POLICY: Record<AttendanceStatus, AttendancePolicyItem> = {
  [AttendanceStatus.PRESENTE]: {
    countsAsPresence: true,
    countsAsAbsence: false,
    isJustifiedAbsence: false,
    reliabilityImpact: 2,
    engagementImpact: 2,
    eligibilityImpact: 2,
    pastoralAlert: false,
    triggersJourneyEvent: true,
    includedInAnalytics: true,
    includedInReports: true,
    includedInDashboard: true,
    generatesTimeline: true,
    triggersAutomation: true,
    severity: 'POSITIVE',
  },
  [AttendanceStatus.FALTA]: {
    countsAsPresence: false,
    countsAsAbsence: true,
    isJustifiedAbsence: false,
    reliabilityImpact: -2,
    engagementImpact: -1,
    eligibilityImpact: -2,
    pastoralAlert: false,
    triggersJourneyEvent: true,
    includedInAnalytics: true,
    includedInReports: true,
    includedInDashboard: true,
    generatesTimeline: true,
    triggersAutomation: true,
    severity: 'MEDIUM',
  },
  [AttendanceStatus.FALTA_JUSTIFICADA]: {
    countsAsPresence: false,
    countsAsAbsence: true,
    isJustifiedAbsence: true,
    reliabilityImpact: 0,
    engagementImpact: 0,
    eligibilityImpact: 0,
    pastoralAlert: false,
    triggersJourneyEvent: true,
    includedInAnalytics: true,
    includedInReports: true,
    includedInDashboard: true,
    generatesTimeline: true,
    triggersAutomation: true,
    severity: 'LOW',
  },
  [AttendanceStatus.LATE]: {
    countsAsPresence: true,
    countsAsAbsence: false,
    isJustifiedAbsence: false,
    reliabilityImpact: -1,
    engagementImpact: 1,
    eligibilityImpact: -1,
    pastoralAlert: false,
    triggersJourneyEvent: true,
    includedInAnalytics: true,
    includedInReports: true,
    includedInDashboard: true,
    generatesTimeline: true,
    triggersAutomation: true,
    severity: 'LOW',
  },
  [AttendanceStatus.LEFT_EARLY]: {
    countsAsPresence: true,
    countsAsAbsence: false,
    isJustifiedAbsence: false,
    reliabilityImpact: -1,
    engagementImpact: 0,
    eligibilityImpact: -1,
    pastoralAlert: false,
    triggersJourneyEvent: true,
    includedInAnalytics: true,
    includedInReports: true,
    includedInDashboard: true,
    generatesTimeline: true,
    triggersAutomation: true,
    severity: 'LOW',
  },
  [AttendanceStatus.EXCUSED_ABSENCE]: {
    countsAsPresence: false,
    countsAsAbsence: true,
    isJustifiedAbsence: true,
    reliabilityImpact: 0,
    engagementImpact: 0,
    eligibilityImpact: 0,
    pastoralAlert: false,
    triggersJourneyEvent: true,
    includedInAnalytics: true,
    includedInReports: true,
    includedInDashboard: true,
    generatesTimeline: true,
    triggersAutomation: true,
    severity: 'LOW',
  },
  [AttendanceStatus.SUBSTITUTED]: {
    countsAsPresence: true,
    countsAsAbsence: false,
    isJustifiedAbsence: false,
    reliabilityImpact: 0,
    engagementImpact: 1,
    eligibilityImpact: 0,
    pastoralAlert: false,
    triggersJourneyEvent: true,
    includedInAnalytics: true,
    includedInReports: true,
    includedInDashboard: true,
    generatesTimeline: true,
    triggersAutomation: true,
    severity: 'LOW',
  },
  [AttendanceStatus.EXTRA_SERVICE]: {
    countsAsPresence: true,
    countsAsAbsence: false,
    isJustifiedAbsence: false,
    reliabilityImpact: 3,
    engagementImpact: 3,
    eligibilityImpact: 2,
    pastoralAlert: false,
    triggersJourneyEvent: true,
    includedInAnalytics: true,
    includedInReports: true,
    includedInDashboard: true,
    generatesTimeline: true,
    triggersAutomation: true,
    severity: 'POSITIVE',
  },
  [AttendanceStatus.NO_SHOW]: {
    countsAsPresence: false,
    countsAsAbsence: true,
    isJustifiedAbsence: false,
    reliabilityImpact: -4,
    engagementImpact: -2,
    eligibilityImpact: -4,
    pastoralAlert: true,
    triggersJourneyEvent: true,
    includedInAnalytics: true,
    includedInReports: true,
    includedInDashboard: true,
    generatesTimeline: true,
    triggersAutomation: true,
    severity: 'HIGH',
  },
  [AttendanceStatus.CANCELLED_SERVICE]: {
    countsAsPresence: false,
    countsAsAbsence: false,
    isJustifiedAbsence: false,
    reliabilityImpact: 0,
    engagementImpact: 0,
    eligibilityImpact: 0,
    pastoralAlert: false,
    triggersJourneyEvent: false,
    includedInAnalytics: false,
    includedInReports: false,
    includedInDashboard: false,
    generatesTimeline: true,
    triggersAutomation: false,
    severity: 'NEUTRAL',
  },
  [AttendanceStatus.UNKNOWN]: {
    countsAsPresence: false,
    countsAsAbsence: false,
    isJustifiedAbsence: false,
    reliabilityImpact: 0,
    engagementImpact: 0,
    eligibilityImpact: 0,
    pastoralAlert: false,
    triggersJourneyEvent: false,
    includedInAnalytics: false,
    includedInReports: false,
    includedInDashboard: false,
    generatesTimeline: false,
    triggersAutomation: false,
    severity: 'NEUTRAL',
  },
};

