-- Expand attendance status enum for operational and pastoral flows
ALTER TYPE "AttendanceStatus" ADD VALUE IF NOT EXISTS 'LATE';
ALTER TYPE "AttendanceStatus" ADD VALUE IF NOT EXISTS 'LEFT_EARLY';
ALTER TYPE "AttendanceStatus" ADD VALUE IF NOT EXISTS 'EXCUSED_ABSENCE';
ALTER TYPE "AttendanceStatus" ADD VALUE IF NOT EXISTS 'SUBSTITUTED';
ALTER TYPE "AttendanceStatus" ADD VALUE IF NOT EXISTS 'EXTRA_SERVICE';
ALTER TYPE "AttendanceStatus" ADD VALUE IF NOT EXISTS 'NO_SHOW';
ALTER TYPE "AttendanceStatus" ADD VALUE IF NOT EXISTS 'CANCELLED_SERVICE';
ALTER TYPE "AttendanceStatus" ADD VALUE IF NOT EXISTS 'UNKNOWN';
